### ISSUE TITLE
Unable to install compass

### ISSUE THREAD

**Issue by zxxz** [jsadowski/generator-jquery-bootstrap-simple#1]
Hello,
On a Mac running El Capitan I had to:
`sudo gem update --system`
`sudo gem install -n /usr/local/bin compass`
instead of:
`gem update --system`
`gem install compass`
I hope this might help others.
Thank you for the generator!

**Comment by jsadowski** [comment]
Hi :),
Thank you for your participation.
I have added description in README file with these commands.
Have a nice day :)
